CREATE DATABASE IF NOT EXISTS github_mysql_260513
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_general_ci;

USE github_mysql_260513;

CREATE TABLE IF NOT EXISTS brands (
	brand_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    brand_name VARCHAR(100) NOT NULL UNIQUE
);

SHOW TABLES;

DESC brands;